name = "VolSurfaceAnalysis"
uuid = "b18484be-7c68-40cd-be13-c5bda9828903"
version = "1.0.0-DEV"
authors = ["aleCombi <alecombi94@gmail.com> and contributors"]

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
ChenSignatures = "4efb4129-5e83-47d2-926d-947c0e6cb76d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
ChenSignatures = "0.4.0"
DataFrames = "1.8.1"
Dates = "1.11.0"
DuckDB = "1.4.1"
Parquet2 = "0.2.33"
Plots = "1.41.4"
Roots = "2.2.10"
TimeZones = "1.22.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
