[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
VolSurfaceAnalysis = "b18484be-7c68-40cd-be13-c5bda9828903"

[sources]
VolSurfaceAnalysis = {path = ".."}
